// <auto-generated />
namespace MVC_Webapp_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_app : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_app));
        
        string IMigrationMetadata.Id
        {
            get { return "202402130811286_user_app"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
