//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASCADING_DROPDOWN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        public int CITYID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<int> STATEIDCOLUMN { get; set; }
    
        public virtual STATE STATE { get; set; }
    }
}
