--CREATING TABLE NAMED EMPLOYEE HAVING COLUMNS EMPLOYEENAME,EMPLOYEEDEPARTMENT--
CREATE TABLE EMPLOYEE(
EMPLOYEENAME NVARCHAR(100) PRIMARY KEY,
EMPLOYEEDEPARTMENT INT,
);
--INSERTING VALUES INTO TABLE--
INSERT INTO EMPLOYEE(EMPLOYEENAME,EMPLOYEEDEPARTMENT)
VALUES
('HYNDHAVI',1),
('RAMYA',2),
('GEETHA',3);
--READING VALUES FROM THE TABLE--
SELECT EMPLOYEENAME, EMPLOYEEDEPARTMENT
FROM EMPLOYEE;
--READING DEPARTMENT1 DETAILS--
SELECT EMPLOYEENAME
FROM EMPLOYEE
WHERE EMPLOYEEDEPARTMENT = 1;
--ADDING NEW COLUMN IN THE TABLE--
ALTER TABLE EMPLOYEE
ADD AGE INT;
--UPDATING THE VALUES--
UPDATE EMPLOYEE
SET AGE  = 22
WHERE EMPLOYEENAME = 'HYNDHAVI';
--SHOW THE STRUCTURE OF TABLE--
SP_help 'EMPLOYEE';
--SHOW THE VALUES OF TABLE--
SELECT*FROM EMPLOYEE;
--DELETING VALUES FROM TABLE--
DELETE FROM EMPLOYEE
WHERE EMPLOYEEDEPARTMENT =3;
--AFTER DELETION OF VALUES,SHOW THE VALUES OF TABLE--
SELECT*FROM EMPLOYEE;
--CREATING STORED PROCEDURE FOR THE GET EMPLOYEE BY DEPARTMENT--
CREATE PROCEDURE Getemployeebydepartment 
@EMPLOYEEDEPARTMENT INT
AS
BEGIN
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEEDEPARTMENT = @EMPLOYEEDEPARTMENT;
END;
--executing stored procedure--
EXECUTE Getemployeebydepartment @EMPLOYEEDEPARTMENT = 1;

--CREATING PROCEDURE FOR INSERTION--
CREATE PROCEDURE InsertEmployee
@EMPLOYEENAME NVARCHAR(100),
@EMPLOYEEDEPARTMENT INT,
@AGE INT
AS
BEGIN
    INSERT INTO EMPLOYEE (EMPLOYEENAME, EMPLOYEEDEPARTMENT, AGE)
    VALUES (@EMPLOYEENAME,@EMPLOYEEDEPARTMENT,@AGE)
END;
--EXECUTING PROCEDURE--
EXECUTE InsertEmployee  @EMPLOYEENAME ='NIKITHA',@EMPLOYEEDEPARTMENT=1,@AGE=22;

--CREATE PROCEDURE FOR UPDATING AGE--
CREATE PROCEDURE UPDATEAGE
(
@AGE INT,
@EMPLOYEENAME NVARCHAR(100)
)
AS
BEGIN
UPDATE EMPLOYEE SET AGE=@AGE WHERE EMPLOYEENAME = @EMPLOYEENAME;
END;
 
 --EXECUTING PROCEDURE--
 EXECUTE UPDATEAGE @EMPLOYEENAME = 'NIKITHA', @AGE = 25;

 SELECT * FROM EMPLOYEE;
 
 --DELETING PROCEDURE--
 CREATE PROCEDURE DELETEPROCEDURE
 (
 @EMPLOYEENAME NVARCHAR(100)
 )
 AS
 BEGIN
 DELETE FROM EMPLOYEE
 WHERE @EMPLOYEENAME =@EMPLOYEENAME
 END;

 --EXECUTING PROCEDURE DELETE--
 EXECUTE DELETEPROCEDURE @EMPLOYEENAME ='RAMYA';